const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'Gmail',
  auth: {
    user: 'raslenouarghi2018@gmail.com',
    pass: 'mforgreygcvhudpt', // Use the app-specific password generated by Google
  },
});

const sendCertificateEmail = (recipientEmail, username, htmlContent) => { // Accept htmlContent parameter
  const mailOptions = {
    from: 'raslenouarghi2018@gmail.com',
    to: recipientEmail,
    subject: 'Congratulations on Getting Your ReactJS Certificate!',
    html: htmlContent, // Use the provided HTML content
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.error('Error sending email:', error);
    } else {
      console.log('Email sent:', info.response);
    }
  });
};

module.exports = {
  sendCertificateEmail,
};
